In [1]:
import pickle
import numpy as np
rf_model = pickle.load(open('RandmForest_model', 'rb'))


C:\Users\willi\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\willi\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\Users\willi\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
tfidf = pickle.load(open('tfidfbasic_model', 'rb'))

In [5]:
def predict(x):
    x = tfidf.transform([x])
    x = x.toarray()
    pred = rf_model.predict(x)
    return pred    

In [6]:
predict('china invades the united states of america')

array([1], dtype=int64)

In [7]:
predict('election was stolen')

array([1], dtype=int64)

In [8]:
predict('5g causes covid')

array([1], dtype=int64)

In [9]:
predict('attacks northern mozambique')

array([1], dtype=int64)

In [10]:
predict('january sixth attack capital')

array([0], dtype=int64)

In [19]:
predict('donald trump wins election')

array([0], dtype=int64)

In [11]:
## After changing wins to won, this was flagged, tried march 10 2022
predict('donald trump won election')

array([1], dtype=int64)

In [12]:
predict('russia invades ukraine')

array([1], dtype=int64)

In [31]:
predict('russia goes war ukraine')

array([1], dtype=int64)

In [14]:
predict('russia attacks ukraine')

array([0], dtype=int64)

In [15]:
predict('joe biden won election')

array([1], dtype=int64)

In [16]:
predict('joe biden wins election')

array([0], dtype=int64)

In [20]:
predict('rhino horn cures cancer')

array([1], dtype=int64)

In [38]:
predict('elephant ivory funds conflict')

array([1], dtype=int64)

In [41]:
predict('corruption undermines democracy')

array([1], dtype=int64)

In [43]:
predict('russia involved with cyberattacks')

array([1], dtype=int64)

In [37]:
##when forgot the e in climate it was predicted as false
predict('climate change real')

array([0], dtype=int64)